#!/bin/sh
#git checkout HEAD -- src/activejdbc/generation_of_xml.md src/activejdbc/caching.md src/activejdbc/validations.md src/activejdbc/database_migrations.md src/activejdbc/instrumentation.md src/activejdbc/lazy_and_eager.md src/activejdbc/converters.md src/activejdbc/in_clause.md src/activejdbc/autogenerated_fields.md src/activejdbc/record_creation.md src/activejdbc/setters_and_getters.md src/activejdbc/eclipseIntegration.md src/activejdbc/one_to_many_associations.md src/activejdbc/transactions.md src/activejdbc/jspec.md src/activejdbc/clob_support_and_caching.md src/activejdbc/polymorphic_associations.md src/activejdbc/sources.md src/activejdbc/many_to_many_associations.md src/activejdbc/documentation.md src/activejdbc/activejdbc_faq.md src/activejdbc/batch_operations.md src/activejdbc/inheritance.md src/activejdbc/getting_started.md src/activejdbc/javadoc.md src/activejdbc/netbeansIntegration.md src/activejdbc/limit_and_sort.md src/activejdbc/data_conversions.md src/activejdbc/surrogate_primary_keys.md src/activejdbc/database_connection_management.md src/activejdbc/intellij_idea_integration.md src/activejdbc/logging.md src/activejdbc/statistics_reporting.md src/activejdbc/http.md src/activejdbc/record_selection.md src/activejdbc/lifecycle_callbacks.md src/activejdbc/generation_of_json.md src/activejdbc/support.md src/activejdbc/activejdbc.md src/activejdbc/optimistic_locking.md src/activejdbc/delete_cascade.md src/activejdbc/writing_tests.md src/activejdbc/ide_integrations.md

git checkout HEAD -- src/activeweb/mvc_pattern.md src/activeweb/getting_started_activeweb.md src/activeweb/routing.md src/activeweb/dependency_injection.md src/activeweb/database_configuration.md src/activeweb/captcha.md src/activeweb/views.md src/activeweb/activeweb.md src/activeweb/controllers.md src/activeweb/lessc.md src/activeweb/testing.md src/activeweb/running_in_development_mode.md src/activeweb/mac_osx.md src/activeweb/app_context.md src/activeweb/deploying_to_heroku.md src/activeweb/flash_tag.md src/activeweb/structure_of_activeweb_project.md src/activeweb/controller_filters.md src/activeweb/five_minute_guide_to_activeweb.md

export DIR=src/activeweb

# Create new files:
for file in `ls $DIR/*.md`; do ./header.sh $file > $file.new; done

#remove .new:
for file in `ls $DIR/*.new`; do echo $file | mv $file `python -c "print raw_input()[:-4]"`; done

#remove h1:
for file in `ls $DIR/*.md` ;do cat $file | grep -v "^# "  > $file.new ; done

#remove .new:
for file in `ls $DIR/*.new`; do echo $file | mv $file `python -c "print raw_input()[:-4]"`; done
